### ISSUE TITLE
Add more common fonts to Font Family dropdown list

### ISSUE THREAD

**Issue by ghost** [KevinParnell/OneeChan#9]
Please add more commonly used fonts to the dropdown list so we don't have to use that crappy font family loader that needs Flash to run.

We need: 

- Deja Vu Sans

- Roboto

- Verdana

- Noto

- PT Sans

- Liberation

- Source Sans

That should cover it unless other people have other additions to make.

**Comment by KevinParnell** [comment]
Noted.

**Comment by Cruxador** [comment]
I want Libre Baskerville, for one thing. I'm not sure it's common enough to justify inclusion, but on my machine the loading from my machine looks broken (I assume because Chrome doesn't play nicely with Flash) but there's not a lot of serif options. I'd reckon that's where additions are needed moreso than a bunch of sans serif fonts.

**Comment by KevinParnell** [comment]
https://github.com/KevinParnell/OneeChan/commit/7071aa124af7c3bdd3c6f6de5cb6c0330ebfcb09

https://github.com/KevinParnell/OneeChan/commit/249a27ab9f9a4ae30be7882b2397f172911ad0d6
